Applying concepts in an Apple clone page.
kenderb/building-with-backgrounds-and-gradients pull request #1
Opened 2020-09-30 20:40 UTC by kenderb

The page contains the next mains tags:

- Main tag and inside a navbar.
- Grid system for the main layout of the page.
- And a foot tag with links and ul tag.

2020-09-30 21:44 UTC, blackpintz requested changes
# Status: Changes Required

### Hello team,

**Great job on your project. However, there are a few fixes needed before the project can be approved.**

### Mandatory

1). **The navbar background image should be generated using a linear gradient and not an image URL.  ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/navigation_requirement.png) from Odin).**

2). **Some of the footer links are displaying on two lines instead of one like in the original. 
Hint: You can also reduce the left and right spacing so the footer doesn't look too narrow.**

original | clone
---------| -------
![applce_original](https://user-images.githubusercontent.com/38922385/94742122-db4d3e80-037d-11eb-941f-79bd6d955928.png) | ![apple_clone](https://user-images.githubusercontent.com/38922385/94742146-e56f3d00-037d-11eb-8034-da5d4552943e.png)

3). **The `nav` tag should not be inside the `main` tag but above it. Please change that.**

### Happy coding 😃.

**PS: You can reach me on slack(Rose Wanjohi).**

2020-10-01 02:42 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

#### Hello, @kenderb and @carloso0114, Great job! 👏  
Both of you have done well on this project and great job on implementing the requested changes
However, there are still some changes that are necessary for this project to be approved.

Please refer to the comments I have made on your code below, fix those and you should be good to go.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-10-01 02:42 UTC, acushlakoncept commented on index.html
> +      </h3>
### Please use actual text instead of a screenshot of the text. 
<img width="985" alt="Screen Shot 2020-10-01 at 3 28 37 AM" src="https://user-images.githubusercontent.com/5264771/94759473-e90fbd80-0397-11eb-92ec-8a41cb967532.png">
. 
<img width="982" alt="Screen Shot 2020-10-01 at 3 27 48 AM" src="https://user-images.githubusercontent.com/5264771/94759466-e4e3a000-0397-11eb-9ef0-745ff1dbcd27.png">
<img width="984" alt="Screen Shot 2020-10-01 at 3 28 06 AM" src="https://user-images.githubusercontent.com/5264771/94759470-e7de9080-0397-11eb-8ce6-70f734aabc25.png">

2020-10-01 05:41 UTC, arslanbisharat approved these changes
h### Congratulations APPROVED :clap:
Hello I can see you worked really hard on this project. and I'm very happy to approve this project with the latest changes you made in this project. :satisfied:
_The clone shows a good understanding and usage of HTML CSS💯_

- The cloned page is rendering as it should and meets all the project specifications.
-  CSS is clean.
-  The markup as well has no errors nor warnings to show. Good job with that.
-  The repo has followed all the guidelines there are to follow.
-  All the required tasks have been fulfilled in this project.
-  Congratulations on the splendid job👍
Now you can merge the branches and move forward with your curriculum. 🎆 

[OPTIONAL] If you wish to delete your currently working branch please update the Live demo link too so that it works properly. 

_Keep working hard._ 

I am very excited to see your next project.

**Happy Coding**:smiley:
------------------------------------------------------------------------------
**Regards,
Arslan Bisharat**
[linkedin](https://www.linkedin.com/in/arslanbisharat/) slack: @arslanbisharat

2020-10-01 15:52 UTC, merged